import type { IMainForm } from '../types';

export const setFormModel = (value?: Partial<IMainForm>): IMainForm => {
  return {
    targetCreditAmount: value?.targetCreditAmount,
    youngSpecialistsCount: value?.youngSpecialistsCount,
    gracePeriod: value?.gracePeriod,
    creditReturnPeriodYears: value?.creditReturnPeriodYears,
    creditSecurityType: value?.creditSecurityType,
    plannedCreditReturnSchedule: value?.plannedCreditReturnSchedule,
    creditReturnFrequency: value?.creditReturnFrequency,
    projectDescription: value?.projectDescription ?? '',
    ownFundsAmount: value?.ownFundsAmount,
    organizationSocialIndicators: value?.organizationSocialIndicators ?? '',
    contactPersonFullName: value?.contactPersonFullName ?? '',
    mobilePhone: value?.mobilePhone ?? '',
    workPhone: value?.workPhone ?? '',
    homePhone: value?.homePhone ?? '',
    email: value?.email ?? '',
    directorFullName: value?.directorFullName ?? '',
    applicantQuestionnaireDocumentUrl: value?.applicantQuestionnaireDocumentUrl ?? '',

    certificateOfStateRegistration: value?.certificateOfStateRegistration ?? '',
    organizationCharter: value?.organizationCharter ?? '',
    foundingAgreement: value?.foundingAgreement ?? '',
    foundersDecisionToOpenOrganization: value?.foundersDecisionToOpenOrganization ?? '',
    foundersDecisionOnTargetLoan: value?.foundersDecisionOnTargetLoan ?? '',
    orderOnTargetLoan: value?.orderOnTargetLoan ?? '',
    ceoAuthorityConfirmation: value?.ceoAuthorityConfirmation ?? '',
    chiefAccountantAuthorityConfirmation: value?.chiefAccountantAuthorityConfirmation ?? '',
    ceoPassport: value?.ceoPassport ?? '',
    chiefAccountantPassport: value?.chiefAccountantPassport ?? '',
    itParkResidencyCertificate: value?.itParkResidencyCertificate ?? '',
    educationActivityPermission: value?.educationActivityPermission ?? '',

    financialStatements: value?.financialStatements ?? '',
    taxDebtAbsenceCertificate: value?.taxDebtAbsenceCertificate ?? '',
    bankAccountCertificate: value?.bankAccountCertificate ?? '',
    projectBusinessPlan: value?.projectBusinessPlan ?? '',
    targetFundSpendingEstimate: value?.targetFundSpendingEstimate ?? '',
    leaseAgreement: value?.leaseAgreement ?? '',

    landCadastrePassport: value?.landCadastrePassport ?? '',
    ownershipDocuments: value?.ownershipDocuments ?? '',
    realEstateValuationReport: value?.realEstateValuationReport ?? '',
    vehicleRegistrationCertificate: value?.vehicleRegistrationCertificate ?? '',
    vehicleValuationReport: value?.vehicleValuationReport ?? '',
    shareholderResolution: value?.shareholderResolution ?? '',
    guarantorFinancialAndFoundingDocs: value?.guarantorFinancialAndFoundingDocs ?? '',
    auditorOpinion: value?.auditorOpinion ?? '',
    guarantorLetter: value?.guarantorLetter ?? '',
    insuranceCompanyLetter: value?.insuranceCompanyLetter ?? '',
  };
};
